### ISSUE TITLE
Can't clone submodules from github

### ISSUE THREAD

**Issue by jsbjair** [spelcaster/customvim#1]
Caminho do sub-módulo 'bundle/nerdtree': confirmado '4ebbb533c3faf2c480211db2b547972bb3b60f2b'
Cloning into '**bundle/nerdtree-git**'...
Warning: Permanently added the RSA host key for IP address '192.30.253.112' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.
fatal: clone of 'git@github.com:Xuyuanp/nerdtree-git-plugin.git' into submodule path 'bundle/nerdtree-git' failed

Solution: change from protocol git to https - git clone https://github.com/Xuyuanp/nerdtree-git-plugin.git bundle/nerdtree-git

Cloning into '**bundle/tsuquyomi'**...
Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:Quramy/tsuquyomi.git' into submodule path 'bundle/tsuquyomi' failed

**Comment by paralelo14** [comment]
noob detected :D
Adiciona tua chave ssh na conta do git e ja era..

**Comment by jsbjair** [comment]
@anarcoder Existe empresas que bloqueiam ssh, e como a maioria dos plugins estão como https, abri a issue, para que seja alterado, para facilitar a vida de quem instala;

**Comment by spelcaster** [comment]
vou alterar todos para ssh e também alterar o modelo de atualização dos módulos de hash para branch, logo, terá a dependência git >= 1.8.2

**Comment by jsbjair** [comment]
git clone https://github.com/universal-ctags/ctags.git, é necessário a instalação do ctags

**Comment by jsbjair** [comment]
@spelcaster só dificultando a vida

**Comment by paralelo14** [comment]
@spelcaster Boto fé de deixar liberado o codigo so para quem nao reclama (@jsbjair) kkkkk

**Comment by spelcaster** [comment]
49c8c8657b55155d05b6a3d27adad394bdb003d6
